
services:
  frontend:
    build:
      context: ./front
    ports:
      - "8080:8080"
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '10m' 
        max-file: '3' 
    restart: always
  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    container_name: backendContainer
    env_file:
      - .env
    depends_on:
      - db
    logging:
      driver: 'json-file'
      options:
        max-size: '10m' 
        max-file: '3' 
    restart: always
  db:
    image: mysql:8.4
    ports:
      - "3306:3306"
    container_name: dbContainer
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
networks:
  default:
    driver: bridge